"""Create initial Project table

Revision ID: 3c3824bea299
Revises: 
Create Date: 2025-10-16 00:27:59.593380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Bu satırı ekleyin
from pgvector.sqlalchemy import Vector  # Bu satırı ekleyin
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c3824bea299'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_login', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('owner_avatar_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('owner_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('owner_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('primary_language', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('languages_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('topics', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('watchers', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('created_at_github', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pushed_at_github', sa.DateTime(timezone=True), nullable=True),
    sa.Column('github_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('homepage_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('readme_content', sa.Text(), nullable=True),
    sa.Column('project_embedding', Vector(768), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_full_name'), 'projects', ['full_name'], unique=True)
    op.create_index(op.f('ix_projects_is_archived'), 'projects', ['is_archived'], unique=False)
    op.create_index(op.f('ix_projects_owner_login'), 'projects', ['owner_login'], unique=False)
    op.create_index(op.f('ix_projects_owner_type'), 'projects', ['owner_type'], unique=False)
    op.create_index(op.f('ix_projects_primary_language'), 'projects', ['primary_language'], unique=False)
    op.create_index(op.f('ix_projects_pushed_at_github'), 'projects', ['pushed_at_github'], unique=False)
    op.create_index(op.f('ix_projects_stars'), 'projects', ['stars'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_stars'), table_name='projects')
    op.drop_index(op.f('ix_projects_pushed_at_github'), table_name='projects')
    op.drop_index(op.f('ix_projects_primary_language'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_login'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_archived'), table_name='projects')
    op.drop_index(op.f('ix_projects_full_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
