name: Deploy Processor Lambda to ECR

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-processor.yml'
      - 'app/tasks/processor.py'
      - 'app/services/data_processing_service.py'
      - 'app/data_access/repositories/project_repository.py'
      - 'app/models/project.py'
      - 'app/external/embedding_client.py'
      - 'app/external/s3_client.py'
      - 'app/services/readme_extractor.py'
      - 'Dockerfile.processor'
      - 'requirements-processor.txt' 
      - 'deployment-helpers/download_model.py'
      

env:
  AWS_REGION: 'eu-central-1'
  ECR_REPOSITORY_PROCESSOR: 'developer-archives-processor' 
  LAMBDA_FUNCTION_NAME_PROCESSOR: 'developer-archives-processor'

jobs:
  deploy-processor:
    name: Build and Deploy Processor
    runs-on: ubuntu-latest
    environment: env
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, cache, and push image to Amazon ECR
      id: build-image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.processor
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_PROCESSOR }}:${{ github.sha }}
        platforms: linux/arm64
        cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_PROCESSOR }}:buildcache
        cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_PROCESSOR }}:buildcache,mode=max

    - name: Set image_uri output
      id: set-output
      run: echo "image_uri=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_PROCESSOR }}:${{ github.sha }}" >> $GITHUB_OUTPUT


    - name: Update Lambda function code
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME_PROCESSOR }} \
          --image-uri ${{ steps.set-output.outputs.image_uri }}